-- pulsur/user-interface-app/db/init.sql

-- Database schema for the User Interface Application (user-interface-app)
-- This schema will store data relevant to user dashboards, saved visualizations,
-- user-specific settings, and data required for MVP dashboard features.

-- Table for Personas (data that might be aggregated or directly shown)
-- This could be a simplified version if personas are mostly generated by a backend algorithm
-- and this app primarily consumes them. Or it could store parameters for persona generation.
CREATE TABLE IF NOT EXISTS personas_mvp_data (
    id SERIAL PRIMARY KEY,
    location VARCHAR(255), -- For filtering
    data_date DATE,        -- For filtering
    persona_identifier VARCHAR(100) NOT NULL, -- e.g., "Tech-Savvy Commuter"
    segment_description TEXT,
    segment_size INTEGER, -- For bubble chart size
    key_motivations TEXT[], -- Array of strings
    key_frustrations TEXT[], -- Array of strings
    -- Other characteristics relevant for display or filtering
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (location, data_date, persona_identifier) -- Ensure data uniqueness for a given context
);

COMMENT ON TABLE personas_mvp_data IS 'Stores aggregated or representative data for personas for MVP dashboard display, filterable by location and date.';

-- Table for Sentiment Scores (could be aggregated daily/weekly per location)
CREATE TABLE IF NOT EXISTS sentiment_scores_mvp (
    id SERIAL PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    score_date DATE NOT NULL,
    sentiment_value DECIMAL(3, 2) NOT NULL, -- e.g., 0.65. Range from -1.00 to 1.00 or 0.00 to 1.00
    trend VARCHAR(50), -- e.g., 'improving', 'declining', 'stable'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (location, score_date)
);

COMMENT ON TABLE sentiment_scores_mvp IS 'Stores time-series sentiment scores for different locations for MVP dashboard display.';

-- Table for Word Cloud Data (words and their weights, could be aggregated daily/weekly per location)
CREATE TABLE IF NOT EXISTS word_cloud_mvp_data (
    id SERIAL PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    data_date DATE NOT NULL,
    word TEXT NOT NULL,
    weight DECIMAL(5, 4) NOT NULL, -- Relative weight/frequency of the word
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (location, data_date, word)
);

COMMENT ON TABLE word_cloud_mvp_data IS 'Stores words and their weights for generating word clouds, filterable by location and date for MVP.';

-- Other potential tables (not strictly for MVP visual components but for app functionality):
-- user_preferences (e.g., saved filters, dashboard layout - for future enhancements)
-- CREATE TABLE IF NOT EXISTS user_preferences (
--     user_id INTEGER NOT NULL, -- Assuming it links to users in identification-app, FK needs careful thought in microservices
--     preference_key VARCHAR(100) NOT NULL,
--     preference_value JSONB,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (user_id, preference_key)
-- );
-- COMMENT ON TABLE user_preferences IS 'Stores user-specific preferences for the interface.';

-- client_users (if 'Principal' user can create sub-accounts managed by this app, as per brief "IAM propres à chaque client")
-- This would require more detailed thought on how users from identification-app are linked here.
-- CREATE TABLE IF NOT EXISTS client_managed_users (
--    id SERIAL PRIMARY KEY,
--    client_principal_user_id INTEGER NOT NULL, -- links to the main client user in identification-app
--    managed_user_login VARCHAR(255) UNIQUE NOT NULL,
--    -- other relevant fields for this managed user specific to UI access control
--    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );
-- COMMENT ON TABLE client_managed_users IS 'Stores users created and managed by a Client Principal for their organization.';
